### PR TITLE
Adding the Thermal FAQ item to all ARD products

### PR DESCRIPTION
**Pull request by benji-glitsos-ga**
* Moved the FAQ item into a reusable component.
* Added component to all ARD products.

### CODE REVIEW

**Comment by benji-glitsos-ga** [comment]
**Preview:**

* https://pr-246-preview.khpreview.dea.ga.gov.au/data/product/dea-surface-reflectance-landsat-5-tm/?tab=faqs
* https://pr-246-preview.khpreview.dea.ga.gov.au/guides/about/faq/

**Comment by benji-glitsos-ga** [comment]
@CEKrause Ready for your review

**Comment by CEKrause** [comment]
@benji-glitsos-ga  This looks great!! Can you please remove this from the Sentinel pages. This only needs to go on the Landsat ARD pages. Sentinel doesn't have a thermal sensor and so doesn't collect thermal data at all.

**Review by CEKrause — CHANGES_REQUESTED** [review]
Can you please remove this from the Sentinel pages and keep only on the Landsat pages.

**Comment by benji-glitsos-ga** [comment]
@CEKrause I've now removed this from the Sentinel products

**Review by CEKrause — CHANGES_REQUESTED** [review]
Sorry!! One more change. Can you please also take it off the OA products. I was back and forth on this, but I don't think it makes sense to have it there either. Thanks Benji!!

**Comment by benji-glitsos-ga** [comment]
All good -- Ive now taken it off the OA products

**Review by CEKrause — APPROVED** [review]
Woohoo!! Looks great. Thanks @benji-glitsos-ga

**Pull request merged**
