### PR TITLE
Product bands tables

### PR DESCRIPTION
**Pull request by benji-glitsos-ga**
**Changes:**

* Added Specifications Bands table content to all products that are indexed in the Open Data Cube.
* Made the aliases in the bands table be linebreak-separated instead of comma-separated.

**Preview:** https://pr-350-preview.khpreview.dea.ga.gov.au/data/

**Note:** Don't merge this branch until merging this other branch from which it is forked: https://github.com/GeoscienceAustralia/dea-knowledge-hub/pull/306

**Reviews:**

* All surface reflectance products - Aaron - Approved
* GeoMAD - James ~~Cedric~~ - Approved
* DEA Land Cover (Landsat) - James - Approved
* DEA Fractional Cover (Landsat) - James - Approved
* DEA Fractional Cover Percentiles (Landsat) - James - Approved
* DEA Mangroves (Landsat) - Claire P - Approved
* DEA Tasseled Cap Percentiles (Landsat) - James ~~Cedric~~ - Approved
* DEA Water Observations (Landsat) - James ~~Cedric~~ - Approved
* DEA Water Observations Statistics (Landsat) - James ~~Cedric~~ - Approved
* DEA Water Observations (Sentinel-2 NRT) - James ~~Cedric~~ - Approved
* DEA High and Low Tide Imagery (Landsat) - Sagar - Approved
* DEA Intertidal - Sagar - Approved
* DEA Intertidal Extents (Landsat) - Sagar - Approved
* DEA Burnt Area Characteristic Layers Sentinel-2 Near Real-Time - Ivan - Approved

### CODE REVIEW

**Comment by OHehir-Aaron** [comment]
In the background, I would consider changing:
"We need to make accurate comparisons of imagery acquired at different times, seasons and geographic locations."
to
"We need to make accurate comparisons of imagery acquired at different time**s of day**, seasons and geographic locations."

**Comment by OHehir-Aaron** [comment]
in background I would consider changing:
"In particular, the light reflected from the Earth’s surface (surface reflectance) is important for monitoring environmental resources – such as agricultural production and mining activities – over time."
To
"In particular, the **energy** reflected from the Earth’s surface (surface reflectance) is important for monitoring environmental resources – such as agricultural production, **forestry** and mining activities – over time."

**Comment by OHehir-Aaron** [comment]
consider the following change under "what this product offers"
"The resolution is a 30 m grid based on the USGS Landsat Collection 1 archive."
to
"The data has a spatial resolution of 30m and sits within the UTM based MGA94 coordinate reference system."

**Comment by OHehir-Aaron** [comment]
consider the following changes under "applications":
add the following below "emergency management"
"- bushfire response
- flood response"

**Comment by OHehir-Aaron** [comment]
Consider removing current "applications" and update to the following:

Agriculture, Forestry
- Discriminating vegetation, crop and timber types
- Monitoring crop and forest harvests
- Determining range readiness, biomass and health
- Determining soil conditions and associations
- Crop production estimates
- Quantifying burn severity
- Crop water stress
- Monitoring deforestation

Land Use and Mapping
- Classifying Land Uses
- Cartographic mapping and updates
- Monitoring urban growth
- Aiding town planning

Coastal and water
- Mapping turbidity
- Mapping shoreline changes
- Mapping reefs and shallow areas
- Tracking beach erosion and flooding
- Monitoring coral health
- Measuring sea surface temperature 

Environmental monitoring
- Monitoring deforestation
- Monitoring water pollution
- Assessing drought impact
- Tracking oil spills
- Monitoring mine waste pollution
- Assessing carbon stocks
- Atmospheric modelling

**Comment by benji-glitsos-ga** [comment]
Additional comments from Aaron:

For S2, under "What this product offers" I would suggest changing "The introduction of a maturity concept." to just "Maturity"

I think we should add the maturity section to the Landsat descriptions as well

**Comment by benji-glitsos-ga** [comment]
All bands tables have been approved by stakeholders.

**Pull request merged**
