### PR TITLE
add CLUM2023 external metadata page to knowledge hub

### PR DESCRIPTION
**Pull request by erialC-P**
* [x ] I have spellchecked my content using Microsoft Word, Grammarly, or otherwise.
* [ ] If required, update the [DEA Tech Alerts and Changelog][TechAlertsChangelog] and the [DEA Sandbox Updates banner][SandboxUpdatesBanner].

[TechAlertsChangelog]: https://github.com/GeoscienceAustralia/dea-knowledge-hub/blob/main/docs/tech-alerts-changelog/_tech_alerts_changelog.md
[SandboxUpdatesBanner]: https://bitbucket.org/geoscienceaustralia/datakube-apps/src/64c28bbf3d0e019d8940547a22f78b9bfd58d739/clusters/dea-sandbox/sandbox.yaml

### CODE REVIEW

**Review by erialC-P — COMMENTED** [review]
Not sure if this warrants promotion anywhere? e.g Sandbox Banner, Changelog or inclusion in future newsletter?

**Review by benji-glitsos-ga — APPROVED** [review]
This is perfect @erialC-P

**Comment by benji-glitsos-ga** [comment]
I'll gain approval from this before we push it live.

**Comment by benji-glitsos-ga** [comment]
Preview - https://pr-262-preview.khpreview.dea.ga.gov.au/data/external-data/abares-clum-2023/

**Pull request merged**
