### PR TITLE
Include link to expanded grid

### PR DESCRIPTION
**Pull request by JM-GA**
Include link to expanded grid. New grid has been uploaded to production

### CODE REVIEW

**Comment by benji-glitsos-ga** [comment]
@JM-GA I just made a minor edit

**Comment by robbibt** [comment]
Hey @JM-GA, what's the difference between these two files?

- https://data.dea.ga.gov.au/derivative/ga_summary_grid_c3_extended_mapping.geojson
- https://data.dea.ga.gov.au/derivative/ga_summary_grid_c3_expanded.geojson

**Comment by JM-GA** [comment]
Hi @robbibt, I created a mapping between old and new grids, but then I realised someone had already created one that was stored in dev. I have removed the one I created, and copied the one from dev into prod

**Review by benji-glitsos-ga — APPROVED** [review]

**Comment by robbibt** [comment]
Hey @JM-GA, this is likely my fault as I think I originally generated this grid, but just noticed that we have some weird issues down in the south:
image

If yours doesn't have this problem, perhaps we could upload it and rename it "ga_summary_grid_c3_expanded.geojson"?

**Comment by JM-GA** [comment]
Thanks for checking @robbibt, I have swapped it out with my version - it seems to be ok

**Pull request merged**
