### PR TITLE
New content section: Which DEA Services to use?

### PR DESCRIPTION
**Pull request by benji-glitsos-ga**
**Preview:** https://pr-308-preview.khpreview.dea.ga.gov.au/guides/setup/README/

**Changes made:**

* New content section: Which DEA Services to use?
* Edited entire Getting started guide
* Made the Getting started guide the first article in sidebar and moved 'About DEA' to the Appendix
* Added 'DEA Notebooks' callout box to Jupyter user guide

For Knowledge Request: Log request for minor KH updates

Based on [Claire P's Word document](https://geoscienceau.sharepoint.com/:w:/r/sites/DEGroup/_layouts/15/Doc.aspx?sourcedoc=%7B4BD0E288-ECD4-436B-A207-931DA89F65C7%7D&file=DEA%20Services%20on%20a%20page%20-%20draft.docx&wdOrigin=TEAMS-WEB.teams_ns.rwc&action=default&mobileredirect=true)

* [x] I have spellchecked my content using Microsoft Word, Grammarly, or otherwise.
* [ ] If required, update the [DEA Tech Alerts and Changelog][TechAlertsChangelog] and the [DEA Sandbox Updates banner][SandboxUpdatesBanner].

[TechAlertsChangelog]: https://github.com/GeoscienceAustralia/dea-knowledge-hub/blob/main/docs/tech-alerts-changelog/_tech_alerts_changelog.md
[SandboxUpdatesBanner]: https://bitbucket.org/geoscienceaustralia/datakube-apps/src/64c28bbf3d0e019d8940547a22f78b9bfd58d739/clusters/dea-sandbox/sandbox.yaml

### CODE REVIEW

**Comment by robbibt** [comment]
Hey @benji-glitsos-ga, this is looking awesome. Just one thought: the user guides page is already busy and packed with material... is there any way we could streamline/combine any of the following docs? There's already some overlap here, and I just think the cleaner we can get these guides, the easier it will be for users to digest them...

image

**Comment by benji-glitsos-ga** [comment]
Hi @robbibt , yep, I'll look into combining this into the Getting Started with DEA guide.

**Comment by benji-glitsos-ga** [comment]
Hi @erialC-P , this is now ready for review. See the preview: https://pr-308-preview.khpreview.dea.ga.gov.au/guides/setup/README/

**Review by erialC-P — APPROVED** [review]
This looks great Benji, thank you for your work on it! I like the distinction between using DEA Services vs DEA Products and the matrix looks really super. You've done a great job!!

**Pull request merged**
