### PR TITLE
Adding the 'Follow our newsletter' link to the Tech Alerts page

### PR DESCRIPTION
**Pull request by benji-glitsos-ga**
* [x] I have spellchecked my content using Microsoft Word, Grammarly, or otherwise.
* [ ] If required, update the [DEA Tech Alerts and Changelog](TechAlertsChangelog) and the [DEA Sandbox Updates banner](SandboxUpdatesBanner).

[TechAlertsChangelog]: https://github.com/GeoscienceAustralia/dea-knowledge-hub/blob/main/docs/tech-alerts-changelog/_tech_alerts_changelog.md
[SandboxUpdatesBanner]: https://bitbucket.org/geoscienceaustralia/datakube-apps/src/64c28bbf3d0e019d8940547a22f78b9bfd58d739/clusters/dea-sandbox/sandbox.yaml

* I also made the Markdown code slightly more readable by shifting some comments to the top.
* I moved both links to the intro paragraph at the top.
* I renamed the DEA Status Status banner to 'System status of DEA'

### CODE REVIEW

**Comment by benji-glitsos-ga** [comment]
**Preview:** <https://pr-215-preview.khpreview.dea.ga.gov.au/tech-alerts-changelog/>

**Review by CEKrause — APPROVED** [review]
Can you reword to "subscribe to our newsletter"? rather than "follow"?

**Comment by CEKrause** [comment]
Otherwise it looks good.

**Comment by benji-glitsos-ga** [comment]
The "Follow our newsletter" wording was taken from the homepage of the knowledge hub. I think 'subscribe' is better, however, this [DEA Newsletter](https://www.dea.ga.gov.au/news/dea-newsletter-and-communications-archive) page could be improved by making subscribing easier for the user.

ksnip_20240520-123458

**Comment by CEKrause** [comment]
Can we change to subscribe there too? I have already spoken with Nick and he is already making changes to the page on the DEA website where users can subscribe to the newsletter. He's trying to get a direct link, but for now, we can just keep linking to the newsletter page.

**Pull request merged**
